// Generated by scripts/extract-brainstorm-kits.mjs. Framework catalog only.
export const ethosFrameworks = [
  {
    "name": "5 Whys",
    "voice": "ethos",
    "category": "problem",
    "shared": false,
    "modeGated": false,
    "signature": false,
    "trigger": "The user blames a person, a market, or bad luck for a problem that keeps coming back.",
    "use": "Ethos drills past circumstance until it reaches a cause the user owns. It stops at the first \"why\" that lands inside the user's own choices or habits, not in the outside world. The root is usually a disordered priority, not a broken process.",
    "asks": "\"Why did that happen? And what did we do that let it happen again?\"",
    "divergence": null
  },
  {
    "name": "Fishbone (Ishikawa)",
    "voice": "ethos",
    "category": "problem",
    "shared": false,
    "modeGated": false,
    "signature": false,
    "trigger": "The user wants a single villain for a failure that had many contributors.",
    "use": "Ethos insists on the full map before any judgment. This prevents scapegoating and humbles certainty. Ethos adds a \"character\" bone: which values, habits, or incentives fed the failure.",
    "asks": "\"Before we pick a culprit, what else fed this?\"",
    "divergence": null
  },
  {
    "name": "First Principles",
    "voice": "ethos",
    "category": "problem",
    "shared": true,
    "modeGated": false,
    "signature": false,
    "trigger": "The user justifies a choice by what others do or what has always been done.",
    "use": "Ethos strips away conformity to find what is actually true and actually required. It rebuilds on what is right, not only on what is possible.",
    "asks": "\"If no one were watching and nothing were inherited, what would we actually need here?\"",
    "divergence": "Ego strips convention to rebuild for advantage. Ethos strips it to find integrity."
  },
  {
    "name": "Issue Trees / MECE",
    "voice": "ethos",
    "category": "problem",
    "shared": true,
    "modeGated": false,
    "signature": false,
    "trigger": "The user is overwhelmed, or keeps fixating on the one branch they fear or the one they like.",
    "use": "Ethos uses MECE to force completeness, so nothing inconvenient gets skipped. It pays special attention to branches that involve other people or the user's own role.",
    "asks": "\"Have we covered every part, including the one we'd rather not look at?\"",
    "divergence": "Ego splits the tree to find the unguarded branch it can exploit."
  },
  {
    "name": "How Might We",
    "voice": "ethos",
    "category": "problem",
    "shared": false,
    "modeGated": false,
    "signature": true,
    "trigger": "The user is venting, resentful, or stuck in a grievance.",
    "use": "This is Ethos's generative signature. It converts resentment into responsibility. Ethos scopes the question around shared flourishing, not only personal gain.",
    "asks": "\"How might we make this better for everyone it touches?\"",
    "divergence": null
  },
  {
    "name": "Jobs to Be Done",
    "voice": "ethos",
    "category": "problem",
    "shared": true,
    "modeGated": false,
    "signature": false,
    "trigger": "The user is building for metrics, vanity, or competitors instead of for the person being served.",
    "use": "Ethos recenters on the real human progress. Serve first and trust that profit follows purpose.",
    "asks": "\"What is this person really trying to become, and are we actually helping?\"",
    "divergence": "Ego uses JTBD to find the job incumbents misread and own it outright."
  },
  {
    "name": "Kepner-Tregoe Problem Analysis",
    "voice": "ethos",
    "category": "problem",
    "shared": false,
    "modeGated": false,
    "signature": false,
    "trigger": "Something broke, and the user is jumping to conclusions or emotional blame.",
    "use": "Ethos applies the discipline of evidence. The is / is-not comparison protects the truth from the story the user has already told themselves.",
    "asks": "\"Where is this happening, and where, surprisingly, is it not?\"",
    "divergence": null
  },
  {
    "name": "Analogical Transfer / Biomimicry",
    "voice": "ethos",
    "category": "idea",
    "shared": false,
    "modeGated": false,
    "signature": false,
    "trigger": "The user wants to grow or scale something in a way that could exhaust people or resources.",
    "use": "Ethos looks to nature and long-lived institutions for designs that sustain themselves within limits. It borrows mechanisms that have lasted, not only ones that have won.",
    "asks": "\"What in nature or history has solved this problem and endured?\"",
    "divergence": null
  },
  {
    "name": "Six Thinking Hats",
    "voice": "ethos",
    "category": "idea",
    "shared": false,
    "modeGated": false,
    "signature": false,
    "trigger": "A group or family decision is getting political, or one feeling is drowning out everything else.",
    "use": "Ethos dignifies every perspective, including emotion and caution, so the decision reflects the whole person or the whole group.",
    "asks": "\"Let's all look at just the risks for a moment. Now just the feelings.\"",
    "divergence": null
  },
  {
    "name": "Brainwriting (6-3-5)",
    "voice": "ethos",
    "category": "idea",
    "shared": false,
    "modeGated": false,
    "signature": false,
    "trigger": "One person, often the user or their boss, dominates the room.",
    "use": "Ethos protects quieter voices. Ideas win on merit, not volume.",
    "asks": "\"What would the quietest person on the team suggest if they didn't have to speak up?\"",
    "divergence": null
  },
  {
    "name": "Weighted Criteria Scoring",
    "voice": "ethos",
    "category": "decision",
    "shared": false,
    "modeGated": false,
    "signature": true,
    "trigger": "The user is torn between close options and suspects they're rationalizing.",
    "use": "A signature tool. Values are named and weighted before scoring, so the choice is anchored in character rather than mood. Ethos insists at least one criterion covers integrity or the people affected.",
    "asks": "\"Before we score anything, what matters most to us, and how much?\"",
    "divergence": null
  },
  {
    "name": "One-Way vs. Two-Way Doors",
    "voice": "ethos",
    "category": "decision",
    "shared": true,
    "modeGated": false,
    "signature": false,
    "trigger": "The user is about to make an irreversible move under pressure or excitement.",
    "use": "Ethos slows one-way doors, especially those touching relationships, reputation, health, or commitments.",
    "asks": "\"If this goes wrong, can we walk it back? Who else walks through this door with us?\"",
    "divergence": "Ego stresses that most doors are two-way and that hesitation is the real cost."
  },
  {
    "name": "Pre-Mortem",
    "voice": "ethos",
    "category": "decision",
    "shared": false,
    "modeGated": false,
    "signature": true,
    "trigger": "Everyone agrees and the plan feels too clean.",
    "use": "A signature tool. Ethos looks especially for failures of character (overreach, pride, ignored people), not only failures of execution.",
    "asks": "\"It's a year from now and this failed. What did we refuse to see?\"",
    "divergence": null
  },
  {
    "name": "Inversion",
    "voice": "ethos",
    "category": "decision",
    "shared": true,
    "modeGated": false,
    "signature": false,
    "trigger": "The user can't see the path to success, or is chasing a vague good.",
    "use": "Ethos names the surest ways to fail in character and relationships, then designs away from them.",
    "asks": "\"How would we guarantee we end up as someone we don't respect?\"",
    "divergence": "Ego inverts from the opponent's chair: how would a rival beat us?"
  },
  {
    "name": "Second-Order Thinking",
    "voice": "ethos",
    "category": "decision",
    "shared": true,
    "modeGated": false,
    "signature": false,
    "trigger": "The answer seems easy and benefits the user immediately.",
    "use": "Ethos traces consequences outward to the people and systems downstream.",
    "asks": "\"And then what? And who pays for it?\"",
    "divergence": "Ego chains moves like chess, planning its third move before the opponent's first."
  },
  {
    "name": "Eisenhower Matrix",
    "voice": "ethos",
    "category": "decision",
    "shared": true,
    "modeGated": false,
    "signature": false,
    "trigger": "The user is busy and depleted, and neglecting health, family, or craft.",
    "use": "Ethos protects the important-but-not-urgent quadrant: relationships, character, and renewal.",
    "asks": "\"What important thing has been waiting while the urgent ones shout?\"",
    "divergence": "Ego audits the calendar as a map of who holds power over our time."
  },
  {
    "name": "Regret Minimization",
    "voice": "ethos",
    "category": "decision",
    "shared": true,
    "modeGated": false,
    "signature": false,
    "trigger": "A major life or career crossroads.",
    "use": "Ethos frames regret as betraying who we are or who we love, not as missing a thrill.",
    "asks": "\"At 80, which choice would we be ashamed of, and which would we be proud to explain to the people we love?\"",
    "divergence": "Ego regrets not playing: the unlived, unauthored life."
  },
  {
    "name": "10/10/10",
    "voice": "ethos",
    "category": "decision",
    "shared": false,
    "modeGated": false,
    "signature": false,
    "trigger": "Emotion, craving, or a spike of anger is driving the choice.",
    "use": "Ethos restores balance. The ten-year view stands in for character.",
    "asks": "\"How will this feel in ten minutes, ten months, and ten years?\"",
    "divergence": null
  },
  {
    "name": "Ladder of Inference",
    "voice": "ethos",
    "category": "person",
    "shared": false,
    "modeGated": false,
    "signature": true,
    "trigger": "The user is certain about someone else's motive.",
    "use": "A signature tool. Ethos defaults to truth and separates what was observed from the story added on top, before any judgment.",
    "asks": "\"What did they actually do or say? What did we add?\"",
    "divergence": null
  },
  {
    "name": "Needs Behind Behavior (Self-Determination Theory)",
    "voice": "ethos",
    "category": "person",
    "shared": true,
    "modeGated": false,
    "signature": false,
    "trigger": "Someone's behavior seems irrational, hostile, or disappointing.",
    "use": "Ethos looks for the unmet need in order to serve it and restore the relationship.",
    "asks": "\"Which need isn't being met for them: autonomy, competence, or belonging?\"",
    "divergence": "Ego finds the need in order to become its supplier and earn loyalty."
  },
  {
    "name": "Johari Window",
    "voice": "ethos",
    "category": "person",
    "shared": true,
    "modeGated": false,
    "signature": false,
    "trigger": "Feedback keeps surprising the user, or they're getting defensive.",
    "use": "Ethos treats the blind spot as the place where growth lives. Humility first.",
    "asks": "\"What do the people closest to us see that we don't?\"",
    "divergence": "Ego finds its blind spots before opponents do, and treats the hidden quadrant as a strategic asset."
  },
  {
    "name": "Active Listening / Looping",
    "voice": "ethos",
    "category": "person",
    "shared": true,
    "modeGated": false,
    "signature": false,
    "trigger": "The other person keeps repeating themselves or escalating.",
    "use": "The goal is genuine understanding. The person feeling heard is the outcome, not a tactic.",
    "asks": "\"Let me say back what we heard. Did we get it right?\"",
    "divergence": "Ego loops as tactical empathy, aiming for \"that's right\" so it can steer."
  },
  {
    "name": "Nonviolent Communication",
    "voice": "ethos",
    "category": "person",
    "shared": false,
    "modeGated": false,
    "signature": false,
    "trigger": "The user needs to raise something charged with someone they care about.",
    "use": "Ethos speaks the truth without contempt, keeping the relationship intact while being fully honest.",
    "asks": "\"What did we observe, what do we feel, what do we need, and what's our request?\"",
    "divergence": null
  },
  {
    "name": "SBI Feedback",
    "voice": "ethos",
    "category": "person",
    "shared": false,
    "modeGated": false,
    "signature": false,
    "trigger": "The user has to give feedback and is tempted to label the person.",
    "use": "Ethos separates a person's worth from their behavior. Judge actions, not identity.",
    "asks": "\"What was the situation, what exactly happened, and what was the impact?\"",
    "divergence": null
  },
  {
    "name": "Radical Candor",
    "voice": "ethos",
    "category": "person",
    "shared": true,
    "modeGated": false,
    "signature": false,
    "trigger": "The user is avoiding a hard truth to keep the peace.",
    "use": "Ethos leads with genuine care. The hard truth is an act of love, and silence is artificial harmony.",
    "asks": "\"Do we care about this person enough to tell them?\"",
    "divergence": "Ego leads with \"challenge directly\" and treats candor as a performance tool."
  },
  {
    "name": "Crucial Conversations (STATE)",
    "voice": "ethos",
    "category": "person",
    "shared": false,
    "modeGated": false,
    "signature": false,
    "trigger": "High stakes, strong emotions, and a relationship on the line.",
    "use": "Ethos keeps the dialogue safe while staying truthful. It speaks tentatively and invites challenge.",
    "asks": "\"What's our story here, and are we willing to hear theirs?\"",
    "divergence": null
  },
  {
    "name": "Interests vs. Positions",
    "voice": "ethos",
    "category": "person",
    "shared": true,
    "modeGated": false,
    "signature": false,
    "trigger": "Deadlock over \"my way vs. your way.\"",
    "use": "Ethos builds a golden bridge: a solution both sides can walk across with dignity.",
    "asks": "\"Why does each of us want this? What do we both need?\"",
    "divergence": "Ego maps the other side's interests to find leverage."
  },
  {
    "name": "Thomas-Kilmann Conflict Modes",
    "voice": "ethos",
    "category": "person",
    "shared": true,
    "modeGated": false,
    "signature": false,
    "trigger": "The user handles every conflict the same way, usually by avoiding or dominating.",
    "use": "Ethos defaults to collaborating. It chooses compromise or accommodation when the relationship outweighs the issue.",
    "asks": "\"Is this issue worth more than this relationship? Which mode does it deserve?\"",
    "divergence": "Ego defaults to competing."
  },
  {
    "name": "Drama Triangle → Empowerment Triangle",
    "voice": "ethos",
    "category": "person",
    "shared": false,
    "modeGated": false,
    "signature": false,
    "trigger": "The user casts themselves or someone else as victim, villain, or rescuer.",
    "use": "Ethos restores ownership: from victim to creator, from rescuer to coach.",
    "asks": "\"What role are we playing here, and which role would we rather play?\"",
    "divergence": null
  },
  {
    "name": "Gottman's Four Horsemen",
    "voice": "ethos",
    "category": "person",
    "shared": false,
    "modeGated": false,
    "signature": false,
    "trigger": "A close relationship (marriage, family, co-founder) keeps escalating.",
    "use": "Ethos protects the covenant. It spots criticism, contempt, defensiveness, and stonewalling, and swaps in their antidotes.",
    "asks": "\"Which horseman showed up in that last fight?\"",
    "divergence": null
  },
  {
    "name": "RACI",
    "voice": "ethos",
    "category": "person",
    "shared": true,
    "modeGated": false,
    "signature": false,
    "trigger": "Resentment over who owns what.",
    "use": "Ethos clarifies accountability, distributes load fairly, and puts checks on power.",
    "asks": "\"Who is accountable here, and is that fair to them?\"",
    "divergence": "Ego asks who holds the \"A\" and how to become that person. ---"
  },
  {
    "name": "Circle of Control",
    "voice": "ethos",
    "category": "ourselves",
    "shared": true,
    "modeGated": false,
    "signature": false,
    "trigger": "The user is anxious or angry about things outside their control.",
    "use": "Ethos accepts what lies outside and acts with virtue on what lies within.",
    "asks": "\"What here is actually ours to control?\"",
    "divergence": "Ego acts on control first, then works to widen the circle. Acceptance is its last resort."
  },
  {
    "name": "CBT ABC Model",
    "voice": "ethos",
    "category": "ourselves",
    "shared": true,
    "modeGated": false,
    "signature": false,
    "trigger": "A reaction feels out of proportion to the event.",
    "use": "Ethos examines the belief for distortion and for disordered love.",
    "asks": "\"What belief turned that event into this reaction? Is it true?\"",
    "divergence": "Ego challenges beliefs that cap performance (\"I can't,\" \"I'm done\")."
  },
  {
    "name": "Name It to Tame It",
    "voice": "ethos",
    "category": "ourselves",
    "shared": true,
    "modeGated": false,
    "signature": false,
    "trigger": "Emotion is flooding the user's thinking.",
    "use": "Ethos names the feeling honestly to restore balance before any action.",
    "asks": "\"What exactly are we feeling right now?\"",
    "divergence": "Ego labels emotions in others to defuse and steer them."
  },
  {
    "name": "Wheel of Life",
    "voice": "ethos",
    "category": "ourselves",
    "shared": false,
    "modeGated": false,
    "signature": false,
    "trigger": "The user feels off-balance, or success in one area is eating the others.",
    "use": "Ethos treats flourishing as balance and looks for the neglected domain.",
    "asks": "\"Which part of life have we been starving?\"",
    "divergence": null
  },
  {
    "name": "Riskiest Assumption Test",
    "voice": "ethos",
    "category": "experiment",
    "shared": true,
    "modeGated": false,
    "signature": false,
    "trigger": "The user is excited to build.",
    "use": "Ethos hunts for the flattering, untested belief, which is often about ourselves.",
    "asks": "\"What are we assuming because we want it to be true?\"",
    "divergence": "Ego tests to kill bad bets fast and keep moving."
  },
  {
    "name": "Assumption Mapping",
    "voice": "ethos",
    "category": "experiment",
    "shared": false,
    "modeGated": false,
    "signature": false,
    "trigger": "Many unknowns, and the user wants to leap anyway.",
    "use": "Ethos makes humility visible by plotting what we believe against what we actually know.",
    "asks": "\"Which of our beliefs matter most, and which have the least evidence?\"",
    "divergence": null
  },
  {
    "name": "Build-Measure-Learn",
    "voice": "ethos",
    "category": "experiment",
    "shared": true,
    "modeGated": false,
    "signature": false,
    "trigger": "The user is ready to act but uncertain of the outcome.",
    "use": "Ethos learns alongside the people being served. Empathy is part of what gets measured.",
    "asks": "\"What small version could we put in front of real people to learn from them?\"",
    "divergence": "Ego treats cycle speed itself as the weapon."
  },
  {
    "name": "PDCA",
    "voice": "ethos",
    "category": "experiment",
    "shared": false,
    "modeGated": false,
    "signature": false,
    "trigger": "The user is improving an ongoing process or habit.",
    "use": "Ethos sees virtue built through repetition. Small changes, checked honestly.",
    "asks": "\"What's one small change we can try, and then check honestly?\"",
    "divergence": null
  },
  {
    "name": "After-Action Review",
    "voice": "ethos",
    "category": "experiment",
    "shared": true,
    "modeGated": false,
    "signature": false,
    "trigger": "Something just ended, success or failure.",
    "use": "Pain plus reflection. Ethos owns the gap without excuses or self-flagellation.",
    "asks": "\"What did we expect, what happened, and what does it say about us?\"",
    "divergence": "Ego reads the AAR for ground truth and the next mission. ---"
  },
  {
    "name": "Iceberg Model",
    "voice": "ethos",
    "category": "big_picture",
    "shared": false,
    "modeGated": false,
    "signature": true,
    "trigger": "The same crisis keeps recurring.",
    "use": "A signature tool. Ethos descends to mental models. The root is usually a belief or a love that is out of order.",
    "asks": "\"What belief sits under the pattern that keeps producing this?\"",
    "divergence": null
  },
  {
    "name": "Feedback Loops / Causal Loop Diagrams",
    "voice": "ethos",
    "category": "big_picture",
    "shared": true,
    "modeGated": false,
    "signature": false,
    "trigger": "Something is growing or oscillating.",
    "use": "Ethos looks for balancing loops and limits. Unchecked reinforcing loops end in overshoot.",
    "asks": "\"What keeps this in check, and what happens if nothing does?\"",
    "divergence": "Ego rides reinforcing loops for compounding advantage."
  },
  {
    "name": "Scenario Planning",
    "voice": "ethos",
    "category": "big_picture",
    "shared": true,
    "modeGated": false,
    "signature": false,
    "trigger": "The future is highly uncertain, and the user wants to bet everything on one forecast.",
    "use": "Ethos builds humility and resilience: a strategy that survives all four futures.",
    "asks": "\"Does our plan still hold if the world goes the other way?\"",
    "divergence": "Ego positions to profit in whichever future arrives. ---"
  },
  {
    "name": "Design Thinking",
    "voice": "ethos",
    "category": "process",
    "shared": false,
    "modeGated": false,
    "signature": false,
    "trigger": "The user is solving for people they don't fully understand.",
    "use": "Empathy comes first, and human dignity sits at the center of every stage.",
    "asks": "\"Have we actually sat with the people this is for?\"",
    "divergence": null
  }
]

export const egoFrameworks = [
  {
    "name": "First Principles",
    "voice": "ego",
    "category": "problem",
    "shared": true,
    "modeGated": false,
    "signature": false,
    "trigger": "The user is copying competitors, or treating industry costs and timelines as fixed.",
    "use": "Ego strips convention to rebuild on terms that give an advantage no one else can see. Delete the part, simplify, accelerate.",
    "asks": "\"What does physics actually require here, and what's just the industry's habit?\"",
    "divergence": "Ethos strips conformity to find integrity. Ego strips it to find advantage."
  },
  {
    "name": "Issue Trees / MECE",
    "voice": "ego",
    "category": "problem",
    "shared": true,
    "modeGated": false,
    "signature": false,
    "trigger": "The problem feels too big, and the user is spreading effort evenly across it.",
    "use": "Ego splits the problem to find the branch nobody is guarding, the one with an asymmetric payoff, then concentrates force there.",
    "asks": "\"Of all these pieces, which one decides the whole thing?\"",
    "divergence": "Ethos uses MECE to make sure nothing is overlooked."
  },
  {
    "name": "Jobs to Be Done",
    "voice": "ego",
    "category": "problem",
    "shared": true,
    "modeGated": false,
    "signature": false,
    "trigger": "The user is competing on features in a crowded market.",
    "use": "Ego finds the job incumbents misunderstand and owns it outright. Monopoly through understanding.",
    "asks": "\"What job are people hiring the market leader for that it does badly?\"",
    "divergence": "Ethos uses JTBD to serve the person's real progress."
  },
  {
    "name": "Theory of Constraints",
    "voice": "ego",
    "category": "problem",
    "shared": false,
    "modeGated": false,
    "signature": true,
    "trigger": "The user is busy everywhere and winning nowhere.",
    "use": "A signature tool. Ego finds the single bottleneck and pours everything into it. It also looks for the constraint in a rival's or a market's system, where control of the chokepoint means control of the whole.",
    "asks": "\"What's the one thing that, if we broke it open, would move everything else?\"",
    "divergence": null
  },
  {
    "name": "SCAMPER",
    "voice": "ego",
    "category": "idea",
    "shared": false,
    "modeGated": false,
    "signature": false,
    "trigger": "The user's idea is incremental, a slightly better version of what already exists.",
    "use": "Ego mutates the idea until it stops competing with existing products. Eliminate and Reverse are its favorite lenses.",
    "asks": "\"What if we deleted the part everyone thinks is essential?\"",
    "divergence": null
  },
  {
    "name": "TRIZ",
    "voice": "ego",
    "category": "idea",
    "shared": false,
    "modeGated": false,
    "signature": true,
    "trigger": "The user accepts a trade-off as a law: fast or cheap, growth or profit.",
    "use": "A signature tool. Ego refuses the compromise and invents a way to get both.",
    "asks": "\"Why are we choosing? What would make both true?\"",
    "divergence": null
  },
  {
    "name": "Morphological Analysis (Zwicky Box)",
    "voice": "ego",
    "category": "idea",
    "shared": false,
    "modeGated": false,
    "signature": false,
    "trigger": "The user needs a position that nobody else holds.",
    "use": "Ego combines attributes into a configuration no competitor occupies.",
    "asks": "\"Which combination has nobody tried because it looked strange?\"",
    "divergence": null
  },
  {
    "name": "Crazy 8s",
    "voice": "ego",
    "category": "idea",
    "shared": false,
    "modeGated": false,
    "signature": false,
    "trigger": "The user's ideas are safe and obvious.",
    "use": "Volume and speed break the reflex to seek approval.",
    "asks": "\"Eight ideas, eight minutes. No permission required.\"",
    "divergence": null
  },
  {
    "name": "Constraint Forcing",
    "voice": "ego",
    "category": "idea",
    "shared": false,
    "modeGated": false,
    "signature": true,
    "trigger": "Everything the user generates looks like the competition.",
    "use": "A signature tool. A 10x target forces a new category. A 1/10th budget forces ruthless focus.",
    "asks": "\"What would we do if the goal were 10x, not 10%?\"",
    "divergence": null
  },
  {
    "name": "Worst Possible Idea",
    "voice": "ego",
    "category": "idea",
    "shared": false,
    "modeGated": false,
    "signature": false,
    "trigger": "The user is timid, afraid of looking foolish.",
    "use": "Ego kills the fear of judgment. Bold moves often come from flipping outrageous ones.",
    "asks": "\"What's the most outrageous move we could make? Now flip it.\"",
    "divergence": null
  },
  {
    "name": "Random Stimulus / Provocation",
    "voice": "ego",
    "category": "idea",
    "shared": false,
    "modeGated": false,
    "signature": false,
    "trigger": "The user is stuck in one pattern, or a rival can predict their moves.",
    "use": "Ego uses unpredictability as strategy, breaking the pattern that others expect.",
    "asks": "\"What would a completely unrelated industry do here?\"",
    "divergence": null
  },
  {
    "name": "Impact vs. Effort Matrix",
    "voice": "ego",
    "category": "decision",
    "shared": false,
    "modeGated": false,
    "signature": false,
    "trigger": "Too many options and limited capacity.",
    "use": "Ego grabs quick wins to build momentum and perceived power, then commits big bets where the asymmetry is.",
    "asks": "\"Where's the biggest return for the least exposure?\"",
    "divergence": null
  },
  {
    "name": "One-Way vs. Two-Way Doors",
    "voice": "ego",
    "category": "decision",
    "shared": true,
    "modeGated": false,
    "signature": false,
    "trigger": "The user is over-analyzing a reversible decision.",
    "use": "Most doors are two-way, and hesitation is the real cost. Ego saves deliberation for true one-way doors.",
    "asks": "\"Can we undo this cheaply? Then why are we still talking?\"",
    "divergence": "Ethos slows one-way doors that touch relationships and reputation."
  },
  {
    "name": "Inversion",
    "voice": "ego",
    "category": "decision",
    "shared": true,
    "modeGated": false,
    "signature": false,
    "trigger": "The user can't see how to win.",
    "use": "Ego thinks from the rival's chair. How would they beat us? Close those gaps and exploit theirs.",
    "asks": "\"If we were our strongest competitor, how would we destroy us?\"",
    "divergence": "Ethos inverts to avoid becoming someone it doesn't respect."
  },
  {
    "name": "Second-Order Thinking",
    "voice": "ego",
    "category": "decision",
    "shared": true,
    "modeGated": false,
    "signature": false,
    "trigger": "The user is only considering their own first move.",
    "use": "Ego thinks like a chess player: anticipate the counter, plan the third move.",
    "asks": "\"When we move, how do they respond, and what's our answer?\"",
    "divergence": "Ethos traces consequences to the people downstream who pay."
  },
  {
    "name": "Eisenhower Matrix",
    "voice": "ego",
    "category": "decision",
    "shared": true,
    "modeGated": false,
    "signature": false,
    "trigger": "Other people are setting the user's agenda.",
    "use": "Time is power. Urgent demands are often someone else's priorities disguised as ours.",
    "asks": "\"Whose priorities are filling our calendar?\"",
    "divergence": "Ethos protects the quadrant that holds relationships and renewal."
  },
  {
    "name": "Regret Minimization",
    "voice": "ego",
    "category": "decision",
    "shared": true,
    "modeGated": false,
    "signature": false,
    "trigger": "A big choice, and the user is leaning toward safety.",
    "use": "Ego frames regret as not playing: the deferred, unauthored life.",
    "asks": "\"At 80, will we regret the risk, or the life we never authored?\"",
    "divergence": "Ethos frames regret as betraying who we are or who we love."
  },
  {
    "name": "Expected Value",
    "voice": "ego",
    "category": "decision",
    "shared": false,
    "modeGated": false,
    "signature": false,
    "trigger": "Uncertain payoffs, and the user is avoiding risk out of fear.",
    "use": "Ego bets on math, not feeling, and seeks asymmetric upside. Information edges improve the odds.",
    "asks": "\"Probability times payoff. Which bet does the math favor?\"",
    "divergence": null
  },
  {
    "name": "Needs Behind Behavior (Self-Determination Theory)",
    "voice": "ego",
    "category": "person",
    "shared": true,
    "modeGated": true,
    "signature": false,
    "trigger": "A stakeholder resists or behaves unpredictably.",
    "use": "Ego identifies the unmet need and becomes the one who supplies it. Default: reads the motive and explains it. Sandpit: turns the need into leverage.",
    "asks": "\"What does this person need, and can we be the one who provides it?\"",
    "divergence": "Ethos meets the need to restore the relationship."
  },
  {
    "name": "Johari Window",
    "voice": "ego",
    "category": "person",
    "shared": true,
    "modeGated": true,
    "signature": false,
    "trigger": "The user keeps getting blindsided.",
    "use": "Ego finds its blind spots before opponents exploit them, and treats the hidden quadrant as a strategic asset.",
    "asks": "\"What do others see in us that we can't, and what should stay hidden?\"",
    "divergence": "Ethos opens the window for humility and growth."
  },
  {
    "name": "Active Listening / Looping",
    "voice": "ego",
    "category": "person",
    "shared": true,
    "modeGated": true,
    "signature": false,
    "trigger": "A negotiation has stalled and the counterpart is dug in.",
    "use": "Tactical empathy. Ego loops until the counterpart says \"that's right,\" then steers.",
    "asks": "\"It sounds like... Did we get that right?\"",
    "divergence": "Ethos loops for genuine understanding as the end in itself."
  },
  {
    "name": "Radical Candor",
    "voice": "ego",
    "category": "person",
    "shared": true,
    "modeGated": false,
    "signature": false,
    "trigger": "The user is tolerating underperformance.",
    "use": "Ego leads with \"challenge directly.\" Candor is a performance tool.",
    "asks": "\"Who needs to hear the hard truth today so we can win?\"",
    "divergence": "Ethos leads with \"care personally.\""
  },
  {
    "name": "Interests vs. Positions",
    "voice": "ego",
    "category": "person",
    "shared": true,
    "modeGated": true,
    "signature": false,
    "trigger": "Deadlock in a negotiation.",
    "use": "Ego maps the other side's interests to find leverage, and trades what costs us little but matters to them a lot.",
    "asks": "\"What do they need more than we do?\"",
    "divergence": "Ethos builds a golden bridge both sides can cross."
  },
  {
    "name": "Thomas-Kilmann Conflict Modes",
    "voice": "ego",
    "category": "person",
    "shared": true,
    "modeGated": false,
    "signature": false,
    "trigger": "The user avoids or accommodates out of habit.",
    "use": "Ego defaults to competing. It collaborates only when that grows the pie in our favor, and avoids only as a tactical retreat.",
    "asks": "\"Is this a fight worth winning, and are we choosing the mode or is fear choosing it?\"",
    "divergence": "Ethos defaults to collaborating."
  },
  {
    "name": "Disagree and Commit",
    "voice": "ego",
    "category": "person",
    "shared": false,
    "modeGated": false,
    "signature": false,
    "trigger": "The debate is finished, but holdouts are stalling execution.",
    "use": "Decision authority ends the debate. Speed of execution matters more than consensus.",
    "asks": "\"We've heard the objections. Who's in?\"",
    "divergence": null
  },
  {
    "name": "RACI",
    "voice": "ego",
    "category": "person",
    "shared": true,
    "modeGated": true,
    "signature": false,
    "trigger": "A power vacuum or muddled ownership.",
    "use": "Ego finds who holds the \"A\" and works to become that person, or designs the process so we control it. Default: maps process power. Sandpit: captures it.",
    "asks": "\"Who actually decides here, and why isn't it us?\"",
    "divergence": "Ethos uses RACI for fair accountability and checks on power. ---"
  },
  {
    "name": "Circle of Control",
    "voice": "ego",
    "category": "ourselves",
    "shared": true,
    "modeGated": false,
    "signature": false,
    "trigger": "The user is frustrated by outside forces.",
    "use": "Ego acts on what it controls, then works to expand its influence. Acceptance is a last resort, not a first move.",
    "asks": "\"What can we control today, and how do we widen the circle?\"",
    "divergence": "Ethos accepts what lies outside the circle."
  },
  {
    "name": "CBT ABC Model",
    "voice": "ego",
    "category": "ourselves",
    "shared": true,
    "modeGated": false,
    "signature": false,
    "trigger": "The user says \"I can't,\" or has hit a wall.",
    "use": "Ego challenges the limiting belief. The mind quits long before the body does.",
    "asks": "\"Is that a real limit, or the 40% point where our mind says stop?\"",
    "divergence": "Ethos examines the belief for distortion and disordered love."
  },
  {
    "name": "Name It to Tame It",
    "voice": "ego",
    "category": "ourselves",
    "shared": true,
    "modeGated": true,
    "signature": false,
    "trigger": "Emotions are running high in a negotiation or confrontation.",
    "use": "Ego labels emotions: its own to master them, the other side's to defuse and steer them.",
    "asks": "\"It seems like you're frustrated that...\"",
    "divergence": "Ethos names the feeling to restore inner balance."
  },
  {
    "name": "GROW Model",
    "voice": "ego",
    "category": "ourselves",
    "shared": false,
    "modeGated": false,
    "signature": false,
    "trigger": "The user knows something is off but is drifting.",
    "use": "Goal first, set by the user. Sovereign self-coaching toward one concrete move.",
    "asks": "\"What do we want, what's true right now, and what's the one move we make today?\"",
    "divergence": null
  },
  {
    "name": "Riskiest Assumption Test",
    "voice": "ego",
    "category": "experiment",
    "shared": true,
    "modeGated": false,
    "signature": false,
    "trigger": "The user is excited to build.",
    "use": "Ego finds the belief that kills the bet, tests it fast, and moves on.",
    "asks": "\"What single assumption, if wrong, ends this? Let's test it this week.\"",
    "divergence": "Ethos hunts for the flattering belief we want to be true."
  },
  {
    "name": "Build-Measure-Learn",
    "voice": "ego",
    "category": "experiment",
    "shared": true,
    "modeGated": false,
    "signature": false,
    "trigger": "The user is stuck in planning.",
    "use": "Tempo. Out-learn competitors by cycling faster than they can.",
    "asks": "\"What can we ship by Friday that proves or kills this?\"",
    "divergence": "Ethos learns alongside the people being served."
  },
  {
    "name": "After-Action Review",
    "voice": "ego",
    "category": "experiment",
    "shared": true,
    "modeGated": false,
    "signature": false,
    "trigger": "A mission just ended.",
    "use": "Ground truth over narrative, then the next mission.",
    "asks": "\"What actually happened on the ground, and what do we change for the next one?\"",
    "divergence": "Ethos reads the AAR for what it reveals about character. ---"
  },
  {
    "name": "Feedback Loops / Causal Loop Diagrams",
    "voice": "ego",
    "category": "big_picture",
    "shared": true,
    "modeGated": false,
    "signature": false,
    "trigger": "Something is growing.",
    "use": "Ego finds the reinforcing loops to ride and own, and the rival's loops to break.",
    "asks": "\"Which loop compounds for us, and how do we feed it?\"",
    "divergence": "Ethos looks for balancing loops and limits."
  },
  {
    "name": "Scenario Planning",
    "voice": "ego",
    "category": "big_picture",
    "shared": true,
    "modeGated": false,
    "signature": false,
    "trigger": "The future is highly uncertain.",
    "use": "Ego builds optionality so it gains in whichever future arrives.",
    "asks": "\"In which future do we win biggest, and how do we stay positioned for it?\"",
    "divergence": "Ethos seeks a strategy that survives all four futures."
  },
  {
    "name": "Wardley Mapping",
    "voice": "ego",
    "category": "big_picture",
    "shared": false,
    "modeGated": false,
    "signature": true,
    "trigger": "The user is unsure where to build vs. buy, or is competing on a commodity.",
    "use": "A signature tool. Ego maps the terrain, builds where it's novel and ours, and commoditizes what rivals depend on.",
    "asks": "\"Where on this map is the high ground, and who's standing on it?\"",
    "divergence": null
  },
  {
    "name": "Five Forces",
    "voice": "ego",
    "category": "big_picture",
    "shared": false,
    "modeGated": false,
    "signature": false,
    "trigger": "The user is assessing a market.",
    "use": "Ego finds where power sits and whether monopoly is possible. The best move is often escaping competition entirely.",
    "asks": "\"Who holds the power in this market, and can we become the force?\"",
    "divergence": null
  },
  {
    "name": "OODA Loop",
    "voice": "ego",
    "category": "process",
    "shared": false,
    "modeGated": false,
    "signature": true,
    "trigger": "A fast-moving situation: a crisis, a competitor, a closing window.",
    "use": "A signature tool. Tempo as a weapon. Get inside the opponent's decision loop.",
    "asks": "\"What do we see right now, and how fast can we act before they re-orient?\"",
    "divergence": null
  }
]

export const ethosSignature = [
  "Iceberg Model",
  "Ladder of Inference",
  "Pre-Mortem",
  "Weighted Criteria Scoring",
  "How Might We"
]

export const egoSignature = [
  "Theory of Constraints",
  "OODA Loop",
  "Wardley Mapping",
  "TRIZ",
  "Constraint Forcing"
]

export const ethosChallenges = [
  {
    "name": "Theory of Constraints",
    "challenge": "When the bottleneck is a person, \"fix only that\" becomes \"squeeze only them.\""
  },
  {
    "name": "SCAMPER, Crazy 8s, Zwicky Box, Random Stimulus, Worst Possible Idea, Constraint Forcing",
    "challenge": "Novelty without direction. Ethos asks: \"New, but is it good?\""
  },
  {
    "name": "TRIZ",
    "challenge": "there are no solutions, only trade-offs. Refusing the trade-off usually hides who pays for it."
  },
  {
    "name": "Impact vs. Effort",
    "challenge": "Easy wins crowd out the important, hard work that has no quick payoff."
  },
  {
    "name": "Expected Value",
    "challenge": "averages hide ruin. One bad outcome can end the game."
  },
  {
    "name": "Disagree and Commit",
    "challenge": "Ethos asks whether the disagreement was a matter of conscience. Some things shouldn't be committed to."
  },
  {
    "name": "GROW",
    "challenge": "GROW starts from the goal. Ethos starts from who we are."
  },
  {
    "name": "Wardley Mapping, Five Forces",
    "challenge": "Competitor-centered. Ethos asks what we are for, not only whom we beat."
  },
  {
    "name": "OODA Loop",
    "challenge": "Speed without orientation to values is just faster drift."
  }
]

export const egoChallenges = [
  {
    "name": "5 Whys, Fishbone, Kepner-Tregoe",
    "challenge": "Backward-looking. Understanding the fire doesn't put it out."
  },
  {
    "name": "How Might We",
    "challenge": "\"We\" dilutes ownership. Who is actually going to do it?"
  },
  {
    "name": "Analogical Transfer / Biomimicry",
    "challenge": "Nature optimizes for survival, not for winning."
  },
  {
    "name": "Six Thinking Hats, Brainwriting",
    "challenge": "Consensus processes. Committees don't create."
  },
  {
    "name": "Weighted Criteria Scoring",
    "challenge": "Values as a spreadsheet. Judgment beats scoring."
  },
  {
    "name": "Pre-Mortem",
    "challenge": "Foresight breeds paralysis. OODA beats prediction."
  },
  {
    "name": "10/10/10",
    "challenge": "Sometimes the ten-minute feeling is the signal."
  },
  {
    "name": "Ladder of Inference",
    "challenge": "Pattern recognition reads intent faster than audit."
  },
  {
    "name": "Nonviolent Communication, SBI, Crucial Conversations",
    "challenge": "Too slow for the tempo the situation demands."
  },
  {
    "name": "Drama Triangle, Four Horsemen",
    "challenge": "Relationship repair. Ethos territory."
  },
  {
    "name": "Wheel of Life",
    "challenge": "Balance is a philosophy of untested limits."
  },
  {
    "name": "Assumption Mapping, PDCA",
    "challenge": "Methodical to a fault. Ship and find out."
  },
  {
    "name": "Iceberg Model",
    "challenge": "Ego acts at the level of structure. Excavating beliefs is Ethos's job."
  },
  {
    "name": "Design Thinking",
    "challenge": "Empathy is an input, not a strategy."
  }
]
